name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download playlists
        run: |
          echo "#EXTM3U" > combined.m3u

          for url in \
          "https://iptv-org.github.io/iptv/languages/rus.m3u" \
          "https://iptv-org.github.io/iptv/languages/ron.m3u" \
          "https://iptv-org.github.io/iptv/countries/md.m3u"
          do
            curl -s "$url" | grep -v "#EXTM3U" >> combined.m3u
          done

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add combined.m3u
          git commit -m "Update IPTV playlist" || exit 0
          git push
